# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Excel-Template
version:      0.15
version_from: lib/Excel/Template.pm
installdirs:  site
requires:
    File::Basename:                0.01
    IO::File:                      0.01
    IO::Scalar:                    0.01
    Spreadsheet::WriteExcel:       0.42
    Test::Simple:                  0.44
    XML::Parser:                   0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
